name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: backend/package.json
    
    - name: Install dependencies
      run: cd backend && npm ci
    
    - name: Run tests
      run: cd backend && npm test
      
    - name: Notify on success
      if: success()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        details: Backend tests passed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
    - name: Notify on failure
      if: failure()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: error
        details: Backend tests failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check linting
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Notify on failure
      if: failure()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: error
        details: Frontend tests failed!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  deploy-backend:
    needs: [test-backend]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
      
    - name: Notify on deployment
      if: success()
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        details: Backend deployed successfully!
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

